# 1. Set basic system
FROM python:3.12.13

# 2. Set the working directory inside the container
WORKDIR /backend

# 3. Copy requirements to image
COPY requirements.txt requirements.txt

# 4. Install dependencies
RUN pip install update
RUN pip install -r requirements.txt

# 5. Setup expose port for server
EXPOSE 8000

# 7. Keep container alive
ENTRYPOINT ["tail", "-f", "/dev/null"]
