"""init of database

Revision ID: b7ace231ff76
Revises: 
Create Date: 2026-05-04 16:54:56.914586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column
from datetime import datetime

from app.utils.util_store import hash_password

# revision identifiers, used by Alembic.
revision: str = 'b7ace231ff76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_daily_analysis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('chunk_results_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('events_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('events_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_date')
    )

    op.create_table('tb_function_folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_code', sa.String(length=100), nullable=False),
    sa.Column('folder_label', sa.String(length=50), nullable=False),
    sa.Column('default_open', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_code')
    )
    op.create_table('tb_log_batches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('time_from', sa.DateTime(), nullable=False),
    sa.Column('time_to', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('records_fetched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunks_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunks_done', sa.Integer(), server_default='0', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tb_log_batches_status', 'tb_log_batches', ['status'], unique=False)
    op.create_index('idx_tb_log_batches_time_from', 'tb_log_batches', ['time_from'], unique=False)
    op.create_table('tb_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    user_table = table('tb_users',
                       column('id', sa.Integer),
                       column('name', sa.String),
                       column('email', sa.String),
                       column('password_hash', sa.String),
                       column('updated_by', sa.Integer),
                       )
    admin_password = hash_password('admin_dev')
    op.bulk_insert(user_table, [
        {'id':1, 'name': 'admin', 'email': 'admin@mpinfo.com.tw', 'password_hash': admin_password, 'update_by': None},
    ])

    op.create_table('tb_chunk_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['tb_log_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tb_chunk_results_batch_id', 'tb_chunk_results', ['batch_id'], unique=False)
    op.create_index('idx_tb_chunk_results_status', 'tb_chunk_results', ['status'], unique=False)
    op.create_table('tb_function_items',
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('function_code', sa.String(length=100), nullable=False),
    sa.Column('function_label', sa.String(length=50), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['tb_function_folder.id'], ),
    sa.PrimaryKeyConstraint('function_id'),
    sa.UniqueConstraint('function_code')
    )
    op.create_table('tb_security_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('star_rank', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affected_summary', sa.String(length=100), nullable=False),
    sa.Column('affected_detail', sa.Text(), nullable=True),
    sa.Column('current_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('match_key', sa.String(length=200), nullable=False),
    sa.Column('detection_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('continued_from', sa.BigInteger(), nullable=True),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('suggests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ioc_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mitre_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('star_rank BETWEEN 1 AND 5', name='ck_tb_security_events_star_rank'),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['tb_users.id'], ),
    sa.ForeignKeyConstraint(['continued_from'], ['tb_security_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tb_security_events_current_status', 'tb_security_events', ['current_status'], unique=False)
    op.create_index('idx_tb_security_events_event_date', 'tb_security_events', ['event_date'], unique=False)
    op.create_index('idx_tb_security_events_match_key', 'tb_security_events', ['match_key'], unique=False)
    op.create_index('idx_tb_security_events_star_rank', 'tb_security_events', [sa.literal_column('star_rank DESC')], unique=False)
    op.create_table('tb_token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_jti', sa.String(length=255), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_jti')
    )
    op.create_table('tb_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['tb_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('tb_event_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['tb_security_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tb_event_history_event_id', 'tb_event_history', ['event_id'], unique=False)
    op.create_table('tb_role_function',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['tb_function_items.function_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['tb_roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'function_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_role_function')
    op.drop_index('idx_tb_event_history_event_id', table_name='tb_event_history')
    op.drop_table('tb_event_history')
    op.drop_table('tb_user_roles')
    op.drop_table('tb_token_blacklist')
    op.drop_index('idx_tb_security_events_star_rank', table_name='tb_security_events')
    op.drop_index('idx_tb_security_events_match_key', table_name='tb_security_events')
    op.drop_index('idx_tb_security_events_event_date', table_name='tb_security_events')
    op.drop_index('idx_tb_security_events_current_status', table_name='tb_security_events')
    op.drop_table('tb_security_events')
    op.drop_table('tb_function_items')
    op.drop_index('idx_tb_chunk_results_status', table_name='tb_chunk_results')
    op.drop_index('idx_tb_chunk_results_batch_id', table_name='tb_chunk_results')
    op.drop_table('tb_chunk_results')
    op.drop_table('tb_users')
    op.drop_table('tb_roles')
    op.drop_index('idx_tb_log_batches_time_from', table_name='tb_log_batches')
    op.drop_index('idx_tb_log_batches_status', table_name='tb_log_batches')
    op.drop_table('tb_log_batches')
    op.drop_table('tb_function_folder')
    op.drop_table('tb_daily_analysis')
    # ### end Alembic commands ###
